### ISSUE TITLE
MathMl format is not supporting 

### ISSUE THREAD

**Issue by xavyronaldo12** [alawatthe/MathLib#4]
How to support Mathml format using this library
<?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE math PUBLIC "-//W3C//DTD MathML 2.0//EN"
           "http://www.w3.org/Math/DTD/mathml2/mathml2.dtd">
  <math xmlns="http://www.w3.org/1998/Math/MathML">
    <mrow>
      <mi>a</mi>
      <mo>&InvisibleTimes;</mo>
      <msup>
        <mi>x</mi>
        <mn>2</mn>
      </msup>
      <mo>+</mo>
      <mi>b</mi>
      <mo>&InvisibleTimes; </mo>
      <mi>x</mi>
      <mo>+</mo>
      <mi>c</mi>
    </mrow>
  </math>

**Comment by alawatthe** [comment]
@xavyronaldo12 thank you for your question!
You can parse (Content) MathML like so

```js
MathLib.Expression.parseContentMathML('<cn type="rational">3<sep/>4</cn>')
```
I hope this helps.

Please also note, that I didn't do much developement for the currently released MathLib in the last few months, as I am currently thinking about the future of MathLib.
